apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %%NAME%%
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: %%NAME%%
        managedBy: postgresql-operator
    spec:
      containers:
        - name: postgresql
          image: postgres
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_USER
            value: %%USER%%
          - name: POSTGRES_DB
            value: %%DB%%
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: %%PASSWORD%%
                key: postgresql_password
          volumeMounts:
            - name: postgresql-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-volume
          emptyDir: {}
