apiVersion: v1
kind: Service
metadata:
  name: %%NAME%%
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: %%NAME%%
    managedBy: postgresql-operator
    appReady: ok
  type: NodePort
